modLoader = "javafml"
loaderVersion = "[49,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "create_missiles"
version = "${version}"
displayName = "Create Missiles"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.create_missiles]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_missiles]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_missiles]]
modId = "architectury"
mandatory = true
versionRange = "[11.1.17,)"
ordering = "AFTER"
side = "BOTH"
