modLoader = "javafml"
loaderVersion = "[${forge_version},)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "createmissiles"
version = "${version}"
displayName = "Create Missiles"
authors = ["Woukie", "ExpertSalad"]
description = '''
Create da missile :)
'''
logoFile = "icon.png"

[[dependencies.createmissiles]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.createmissiles]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.createmissiles]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"